import type { Item, User, SwapRequest } from './types';

export const mockUsers: User[] = [
  {
    id: 'user1',
    name: 'Alice',
    avatar: 'https://placehold.co/100x100.png',
    location: 'New York, NY',
    memberSince: new Date('2023-01-15'),
    points: 1250,
  },
  {
    id: 'user2',
    name: 'Bob',
    avatar: 'https://placehold.co/100x100.png',
    location: 'Los Angeles, CA',
    memberSince: new Date('2023-03-22'),
    points: 800,
  },
];

export const mockItems: Item[] = [
  {
    id: 'item1',
    name: 'Vintage Denim Jacket',
    description: 'A classic 90s denim jacket in great condition. Features a slightly oversized fit and medium wash. Perfect for layering.',
    category: 'Outerwear',
    condition: 'Excellent',
    size: 'M',
    images: [
      'https://placehold.co/600x800.png',
      'https://placehold.co/600x800.png',
      'https://placehold.co/600x800.png',
    ],
    points: 300,
    tags: ['denim', 'vintage', '90s', 'jacket'],
    userId: 'user1',
  },
  {
    id: 'item2',
    name: 'Floral Maxi Dress',
    description: 'Beautiful and flowy maxi dress with a vibrant floral pattern. Ideal for summer events or a casual day out. Lightweight fabric.',
    category: 'Dresses',
    condition: 'New with tags',
    size: 'S',
    images: ['https://placehold.co/600x800.png'],
    points: 450,
    tags: ['floral', 'summer', 'maxi dress', 'boho'],
    userId: 'user2',
  },
  {
    id: 'item3',
    name: 'Leather Ankle Boots',
    description: 'Stylish black leather ankle boots with a small heel. Versatile and comfortable for everyday wear. Minimal signs of wear.',
    category: 'Shoes',
    condition: 'Good',
    size: '8',
    images: ['https://placehold.co/600x800.png'],
    points: 250,
    tags: ['leather', 'boots', 'black', 'minimalist'],
    userId: 'user1',
  },
  {
    id: 'item4',
    name: 'Striped Cotton Tee',
    description: 'A soft, 100% cotton t-shirt with classic navy and white stripes. A wardrobe staple.',
    category: 'Tops',
    condition: 'Excellent',
    size: 'L',
    images: ['https://placehold.co/600x800.png'],
    points: 100,
    tags: ['cotton', 'striped', 'basic', 'tee'],
    userId: 'user2',
  },
    {
    id: 'item5',
    name: 'High-Waisted Trousers',
    description: 'Elegant beige high-waisted trousers. Perfect for office or casual smart look.',
    category: 'Bottoms',
    condition: 'Excellent',
    size: 'UK 10',
    images: ['https://placehold.co/600x800.png'],
    points: 280,
    tags: ['trousers', 'high-waisted', 'smart casual'],
    userId: 'user1',
  },
  {
    id: 'item6',
    name: 'Silk Scarf',
    description: 'A beautiful silk scarf with a unique abstract print. Can be worn in multiple ways.',
    category: 'Accessories',
    condition: 'New with tags',
    size: 'One Size',
    images: ['https://placehold.co/600x800.png'],
    points: 180,
    tags: ['silk', 'scarf', 'accessory', 'luxury'],
    userId: 'user2',
  },
  {
    id: 'item7',
    name: 'Wool Peacoat',
    description: 'Classic navy wool peacoat. Double-breasted design. Very warm and stylish for winter.',
    category: 'Outerwear',
    condition: 'Good',
    size: 'M',
    images: ['https://placehold.co/600x800.png'],
    points: 500,
    tags: ['wool', 'winter', 'peacoat', 'classic'],
    userId: 'user1',
  },
  {
    id: 'item8',
    name: 'Linen Blend Shorts',
    description: 'Light and airy linen blend shorts in a neutral khaki color. Perfect for warm weather.',
    category: 'Bottoms',
    condition: 'Excellent',
    size: 'M',
    images: ['https://placehold.co/600x800.png'],
    points: 150,
    tags: ['linen', 'shorts', 'summer', 'casual'],
    userId: 'user2',
  },
];

export const mockSwaps: SwapRequest[] = [
    {
        id: 'swap1',
        itemId: 'item1',
        requesterId: 'user2',
        ownerId: 'user1',
        status: 'pending',
        createdAt: new Date('2024-05-20'),
    },
    {
        id: 'swap2',
        itemId: 'item4',
        requesterId: 'user1',
        ownerId: 'user2',
        status: 'accepted',
        createdAt: new Date('2024-05-18'),
    },
    {
        id: 'swap3',
        itemId: 'item3',
        requesterId: 'user2',
        ownerId: 'user1',
        status: 'declined',
        createdAt: new Date('2024-05-15'),
    }
]
