import type { Item, User, SwapRequest } from './types';

export const mockUsers: User[] = [
  {
    id: 'user1',
    name: 'Alice',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwzfHxtb2RlbHxlbnwwfHx8fDE3NTIzMDE4ODZ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    location: 'New York, NY',
    memberSince: new Date('2023-01-15'),
    points: 1250,
  },
  {
    id: 'user2',
    name: 'Bob',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=400&auto=format&fit=crop',
    location: 'Los Angeles, CA',
    memberSince: new Date('2023-03-22'),
    points: 800,
  },
];

export const mockItems: Item[] = [
  {
    id: 'item1',
    name: 'Vintage Denim Jacket',
    description: 'A classic 90s denim jacket in great condition. Features a slightly oversized fit and medium wash. Perfect for layering.',
    category: 'Outerwear',
    condition: 'Excellent',
    size: 'M',
    images: [
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwzfHxKYWNrZXR8ZW58MHx8fHwxNzUyMzAxOTI1fDA&ixlib=rb-4.1.0&q=80&w=1080',
      'https://images.unsplash.com/photo-1595950653106-6c9ebd614d34?q=80&w=600&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1605902711622-cfb4c194ea38?q=80&w=600&auto=format&fit=crop',
    ],
    points: 300,
    tags: ['denim', 'vintage', '90s', 'jacket'],
    userId: 'user1',
  },
  {
    id: 'item2',
    name: 'Floral Maxi Dress',
    description: 'Beautiful and flowy maxi dress with a vibrant floral pattern. Ideal for summer events or a casual day out. Lightweight fabric.',
    category: 'Dresses',
    condition: 'New with tags',
    size: 'S',
    images: ['https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?q=80&w=600&auto=format&fit=crop'],
    points: 450,
    tags: ['floral', 'summer', 'maxi dress', 'boho'],
    userId: 'user2',
  },
  {
    id: 'item3',
    name: 'Leather Ankle Boots',
    description: 'Stylish black leather ankle boots with a small heel. Versatile and comfortable for everyday wear. Minimal signs of wear.',
    category: 'Shoes',
    condition: 'Good',
    size: '8',
    images: ['https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=600&auto=format&fit=crop'],
    points: 250,
    tags: ['leather', 'boots', 'black', 'minimalist'],
    userId: 'user1',
  },
  {
    id: 'item4',
    name: 'Striped Cotton Tee',
    description: 'A soft, 100% cotton t-shirt with classic navy and white stripes. A wardrobe staple.',
    category: 'Tops',
    condition: 'Excellent',
    size: 'L',
    images: ['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=600&auto=format&fit=crop'],
    points: 100,
    tags: ['cotton', 'striped', 'basic', 'tee'],
    userId: 'user2',
  },
    {
    id: 'item5',
    name: 'High Waisted Leggings',
    description: 'Elegant beige high-waisted trousers. Perfect for office or casual smart look.',
    category: 'Bottoms',
    condition: 'Excellent',
    size: 'UK 10',
    images: ['https://images.unsplash.com/photo-1594623930334-a849c85319b3?q=80&w=600&auto=format&fit=crop'],
    points: 280,
    tags: ['trousers', 'high-waisted', 'smart casual'],
    userId: 'user1',
  },
  {
    id: 'item6',
    name: 'Silk Scarf',
    description: 'A beautiful silk scarf with a unique abstract print. Can be worn in multiple ways.',
    category: 'Accessories',
    condition: 'New with tags',
    size: 'One Size',
    images: ['https://images.unsplash.com/photo-1529139574466-a303027c1d8b?q=80&w=600&auto=format&fit=crop'],
    points: 180,
    tags: ['silk', 'scarf', 'accessory', 'luxury'],
    userId: 'user2',
  },
  {
    id: 'item7',
    name: 'Wool Peacoat',
    description: 'Classic navy wool peacoat. Double-breasted design. Very warm and stylish for winter.',
    category: 'Outerwear',
    condition: 'Good',
    size: 'M',
    images: ['https://images.unsplash.com/photo-1572804013427-4d7ca7268217?q=80&w=600&auto=format&fit=crop'],
    points: 500,
    tags: ['wool', 'winter', 'peacoat', 'classic'],
    userId: 'user1',
  },
  {
    id: 'item8',
    name: 'Linen Blend Shorts',
    description: 'Light and airy linen blend shorts in a neutral khaki color. Perfect for warm weather.',
    category: 'Bottoms',
    condition: 'Excellent',
    size: 'M',
    images: ['https://images.unsplash.com/photo-1617114919956-655f415c1056?q=80&w=600&auto=format&fit=crop'],
    points: 150,
    tags: ['linen', 'shorts', 'summer', 'casual'],
    userId: 'user2',
  },
];

export const mockSwaps: SwapRequest[] = [
    {
        id: 'swap1',
        itemId: 'item1',
        requesterId: 'user2',
        ownerId: 'user1',
        status: 'pending',
        createdAt: new Date('2024-05-20'),
    },
    {
        id: 'swap2',
        itemId: 'item4',
        requesterId: 'user1',
        ownerId: 'user2',
        status: 'accepted',
        createdAt: new Date('2024-05-18'),
    },
    {
        id: 'swap3',
        itemId: 'item3',
        requesterId: 'user2',
        ownerId: 'user1',
        status: 'declined',
        createdAt: new Date('2024-05-15'),
    }
]
